apiVersion: v1
kind: ServiceAccount
metadata:
  name: netheos-operator
  namespace: {{ .Values.netheos.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: netheos
